name = "rec-time-be"
main = "src/index.ts"
#nodeライブラリ互換フラグ
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"

# 開発環境設定
[env.development]
vars = { NODE_ENV = "development", API_URL = "https://localhost:8787", DEBUG = "true" }
# 追加の環境変数例：
# vars = { NODE_ENV = "development", API_URL = "https://localhost:8787", DEBUG = "true", YOUR_API_KEY = "your-api-key-here" }

# ステージング環境設定
[env.staging]
vars = { NODE_ENV = "staging", API_URL = "https://staging-api.your-domain.com", DEBUG = "false" }

# 本番環境設定
[env.production]
vars = { NODE_ENV = "production", CORS_ORIGINS = "https://localhost:5173,https://192.168.10.50:5173", API_URL = "https://api.your-domain.com", DEBUG = "false", LOG_LEVEL = "info" }


# 本番環境用D1データベース設定
[[env.production.d1_databases]]
binding = "DB"
database_name = "your-database-prod"
database_id = "your-production-database-id-here"